### ISSUE TITLE
Emulator loses Focus when Splitting

### ISSUE THREAD

**Issue by Juiin** [gcervantes8/Star-Classifier-For-Mario-64#2]
When splitting, the active window becomes Livesplit instead of the Emulator used to play the game, this causes the emulator to be unable to receive input from my controller. You may have implemented this to make sure the split Hotkey arrives at Livesplit, but this is not necessary because of its Global hotkeys feature. Is there a way to disable this, so that the emulator stays in focus?

**Comment by gcervantes8** [comment]
That makes sense, there is currently no way to disable LiveSplit from being the window in focus when the program splits.  I hadn't tested before on emulator, so I didn't anticipate this would be a problem.  I'll try to push a new release adding this feature within the next day or so.

**Comment by Juiin** [comment]
That sounds awesome, looking very much forward to the 
update.6/29/2020 10:24 PM Gerardo Cervantes (notifications@github.com) 


  
  That makes sense, there is currently no way to disable LiveSplit from being 
  the window in focus when the program splits. I hadn't tested before on 
  emulator, so I didn't anticipate this would be a problem. I'll try to push a 
  new release adding this feature within the next day or so.
  —You 
  are receiving this because you authored the thread.Reply to this email 
  directly, view 
  it on GitHub, or unsubscribe.
  [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gcervantes8/Star-Classifier-For-Mario-64/issues/2#issuecomment-651340982",
"url": "https://github.com/gcervantes8/Star-Classifier-For-Mario-64/issues/2#issuecomment-651340982",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gcervantes8** [comment]
I have fixed this!

The new release (v0.96) can be downloaded from the release page of the GitHub.

Apologies for the wait, this took longer than I anticipated and I spent a lot of time going through many different libraries to find how I should implement this.
